---
- name: Ensure tomcat package is present
  hosts: prod
  become: yes

  roles:
   - common
   - tomcat
   - security

- name: Ensure the application is downloaded
  hosts: build
  become: yes

  roles:
   - common
   - build
...