---
- name: Configuration for production node
  hosts: prod
  become: yes

  roles:
   - common
   - tomcat
   - build
#---------------------------------------------#
- name: Configuration for development node
  hosts: build
  become: yes

  roles:
   - common
   - build
...